### ISSUE TITLE
user chat history does not refresh consistently

### ISSUE THREAD

**Issue by vampserv** [magnetsystems/message-samples-android#24]
1. 3 android clients are members of a group chat.
2. when user1 sends a message, all 3 users receive the message.
3. when user2 or user3 sends a message, only user2 and user3 receive the message.
4. however, when user1 sends a message, user1's chat history gets populated with all of the messages.
   ![screen shot 2016-02-02 at 2 08 57 pm 2](https://cloud.githubusercontent.com/assets/991629/12766133/fb4be85e-c9b6-11e5-920b-01c5330f6819.png)

**Comment by jimxj** [comment]
Fixed
